name: flutter_svg_image
description: An SVG rendering and widget library for Flutter inspired by , which allows painting and displaying Scalable Vector Graphics 1.1 files.
repository:
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  vector_graphics: ^1.1.11+1
  vector_graphics_codec: ^1.1.11+1
  vector_graphics_compiler: ^1.1.11+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

#flutter:

